RegistrationFormUILayer/Models/ErrorViewModel.cs
namespace RegistrationFormUILayer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RegistrationFormUILayer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RegistrationFormUILayer.Models;
using System.Diagnostics;

namespace RegistrationFormUILayer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RegistrationFormUILayer/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using RegistrationFormBusinessLayer;
using RegistrationFormDataAccessLayer;

namespace RegistrationFormUILayer.Controllers
{

    public class RegistrationController : Controller
    {
        BLRegistrationDetails bLRegistrationDetails = new BLRegistrationDetails();
        string result = "";
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// This method get the list of States which are stored in the database
        /// </summary>
        /// <returns></returns>
        public JsonResult getStateList()
        {
            try
            {
                List<StateMaster> stateMasters = new List<StateMaster>();
                stateMasters = bLRegistrationDetails.BLGetStateMasters();
                return Json(stateMasters);
            }
            catch(Exception ex)
            {
                result = ex.Message.ToString();
                return Json(result);
            }
            
        }
        /// <summary>
        /// This method get the list of cities on the based of which state is selected from stored in the database
        /// </summary>
        /// <returns></returns>
        public JsonResult getCitiesList(int StateID)
        {
            try
            {
                List<CityMaster> cityMasters = new List<CityMaster>();
                cityMasters = bLRegistrationDetails.BLGetCitiesMasters(StateID);
                return Json(cityMasters);
            }
            catch(Exception ex)
            {
                result = ex.Message.ToString();
                return Json(result);
            }
            
        }
        /// <summary>
        /// This method will get all the record according to the id passed from the list
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult getRegistrationById(int id)
        {
            try
            {
                List<Register> registers = new List<Register>();
                registers = bLRegistrationDetails.BLGetRegisterfromID(id);
                return Json(registers);
            }
            catch(Exception ex)
            {
                result = ex.Message.ToString();
                return Json(result);
            }
        }
        /// <summary>
        /// get the list of registration details
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult getResgistrationDetails()
        {
            try
            {
                List<Register> registers = new List<Register>();
                registers = bLRegistrationDetails.BLgetAllRegisteration();
                return Json(registers);
            }
            catch(Exception ex)
            {
                result = ex.Message.ToString();
                return Json(result);
            }
            
        } 
        /// <summary>
        /// Save  or update registration data in datatabase
        /// </summary>
        /// <param name="register"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SaveRegistrationdetails(Register register)
        {
            try
            {
                if (register.ID == 0)
                {
                    result = bLRegistrationDetails.BLsaveRegistrationDetails(register);

                }
                else
                {
                    result = bLRegistrationDetails.BLupdateRegistrationDetails(register);
                }
            }
            catch(Exception ex)
            {
                result= ex.Message.ToString();
                
            }
            return Json(result);
        }
        /// <summary>
        /// To delete the record from database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult deleteRegistrationDetails(int id)
        {
            try
            {
                result = bLRegistrationDetails.BLdeleteRegistrationDetails(id);
                return Json(result);
            }
            catch(Exception ex)
            {
                result = ex.Message.ToString();
            }
            return Json(result);
        }      
    }
    
}

RegistrationFormUILayer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RegistrationFormUILayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegistrationFormUILayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RegistrationFormUILayer.styles.css" asp-append-version="true" />
    <script src="~/lib/fontawesome/kitfontawesome.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RegistrationFormUILayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RegistrationFormUILayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.3.7.1.js"></script>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toaster/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>